version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev.dockerfile
      shm_size: 1G
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000