// Newspost reducer
export const TOGGLE_ADD_NEWSPOST_MODAL = "TOGGLE_ADD_NEWSPOST_MODAL";
export const TOGGLE_EDIT_NEWSPOST_MODAL = "TOGGLE_EDIT_NEWSPOST_MODAL";
export const ADD_NEWSPOST = "ADD_NEWSPOST";
export const ADD_NEWSPOST_TO_LIST = "ADD_NEWSPOST_TO_LIST";
export const DELETE_NEWSPOST_FROM_LIST = "DELETE_NEWSPOST_FROM_LIST";
export const SET_NEWSPOSTS = "SET_NEWSPOSTS";
export const REMOVE_NEWSPOST = "REMOVE_NEWSPOST";
export const SET_IS_ADDING_NEWSPOST = "SET_IS_ADDING_NEWSPOST";
export const SET_IS_EDITING_NEWSPOST = "SET_IS_EDITING_NEWSPOST";
export const SET_NEWSPOST_EDIT_ID = "SET_NEWSPOST_EDIT_ID";
// Key reducer
export const ADD_KEY = "ADD_KEY";
export const SET_KEYS = "SET_KEYS";
export const SET_KEY_TYPES = "SET_KEY_TYPES";
export const TOGGLE_KEY_MODAL = "TOGGLE_KEY_MODAL";
// Calendar reducer
export const SET_EVENTS = "SET_EVENTS";
// Authentication reducer
export const SET_IS_LOGGING_IN = "SET_IS_LOGGING_IN";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const DEAUTHENTICATE_USER = "DEAUTHENTICATE_USER";
// Notification reducer
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
