// Newspost reducer
export const TOGGLE_ADD_NEWSPOST_MODAL = "TOGGLE_ADD_NEWSPOST_MODAL";
export const TOGGLE_EDIT_NEWSPOST_MODAL = "TOGGLE_EDIT_NEWSPOST_MODAL";
export const ADD_NEWSPOST = "ADD_NEWSPOST";
export const ADD_NEWSPOST_TO_LIST = "ADD_NEWSPOST_TO_LIST";
export const DELETE_NEWSPOST_FROM_LIST = "DELETE_NEWSPOST_FROM_LIST";
export const SET_NEWSPOSTS = "SET_NEWSPOSTS";
export const REMOVE_NEWSPOST = "REMOVE_NEWSPOST";
export const SET_IS_ADDING_NEWSPOST = "SET_IS_ADDING_NEWSPOST";
export const SET_IS_EDITING_NEWSPOST = "SET_IS_EDITING_NEWSPOST";
export const SET_NEWSPOST_EDIT_ID = "SET_NEWSPOST_EDIT_ID";
// Key reducer
export const ADD_KEY = "ADD_KEY";
export const ADD_KEY_TO_LIST = "ADD_KEY_TO_LIST";
export const SET_KEYS = "SET_KEYS";
export const SET_KEY_TYPES = "SET_KEY_TYPES";
export const TOGGLE_KEY_MODAL = "TOGGLE_KEY_MODAL";
// Calendar reducer
export const SET_EVENTS = "SET_EVENTS";
// Authentication reducer
export const SET_IS_LOGGING_IN = "SET_IS_LOGGING_IN";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const DEAUTHENTICATE_USER = "DEAUTHENTICATE_USER";
// Notification reducer
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
// User reducer
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_TOKEN = "SET_TOKEN";
export const SET_USERS = "SET_USERS";
export const REMOVE_USER = "REMOVE_USER";
export const SET_USER_DATA = "SET_USER_DATA";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const SET_USER_PERMS = "SET_USER_PERMS";
export const DELETE_USER = "DELETE_USER";
// Student union
export const ADD_STUDENT_UNION = "ADD_STUDENT_UNION";
export const DELETE_STUDENT_UNION = "DELETE_STUDENT_UNION";
export const SET_STUDENT_UNIONS = "SET_STUDENT_UNIONS";
export const SET_ADDING_STUDENT_UNION = "SET_ADDING_STUDENT_UNION";
export const ADD_STUDENT_UNION_FORM_MODAL_OPEN =
  "ADD_STUDENT_UNION_FORM_MODAL_OPEN";
export const ADD_STUDENT_UNION_TO_LIST = "ADD_STUDENT_UNION_TO_LIST";
// Session
export const TOGGLE_SESSION_PAGE = "TOGGLE_SESSION_PAGE";
export const FETCH_OWN_SESSION_STATUS = "FETCH_OWN_SESSION_STATUS";
export const SET_OWN_SESSION_STATUS = "SET_OWN_SESSION_STATUS";
export const SET_SESSION_CHECK_INTERVAL = "SET_SESSION_CHECK_INTERVAL";
export const TOGGLE_START_SESSION_MODAL = "TOGGLE_START_SESSION_MODAL";
export const TOGGLE_END_SESSION_MODAL = "TOGGLE_END_SESSION_MODAL";
export const TOGGLE_IS_ENDING = "TOGGLE_IS_ENDING";
export const TOGGLE_IS_STARTING = "TOGGLE_IS_STARTING";
